# Generated by Django 3.1.12 on 2025-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('pendidikan', models.CharField(max_length=50)),
                ('perusahaan_anda', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=30)),
            ],
        ),
    ]
