# Generated by Django 3.1.12 on 2025-02-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='nama_lengkap',
            new_name='nama_akun',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='pendidikan',
            new_name='nomor',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='jenis_kelamin',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='perusahaan_anda',
            new_name='saldo_normal',
        ),
    ]
