# Generated by Django 3.1.12 on 2025-02-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_auto_20250131_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalUmum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kredit', models.IntegerField(blank=True, null=True)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.profil')),
            ],
        ),
    ]
