# Generated by Django 3.1.12 on 2025-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_jurnalumum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='pos',
            field=models.CharField(choices=[('neraca', 'neraca'), ('laba rugi', 'laba rugi')], max_length=30),
        ),
    ]
