# Generated by Django 3.1.12 on 2025-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_auto_20250207_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='pos',
            field=models.CharField(choices=[('laba rugi', 'laba rugi'), ('neraca', 'neraca')], max_length=30),
        ),
    ]
