# Generated by Django 3.1.12 on 2025-02-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_auto_20250207_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='pos',
        ),
        migrations.AddField(
            model_name='profil',
            name='master_akun',
            field=models.CharField(choices=[('aktiva lancar', 'aktiva lancar'), ('aktiva tetap', 'aktiva tetap'), ('passiva', 'passiva'), ('pendapatan', 'pendapatan'), ('beban', 'beban')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
