# Generated by Django 3.1.12 on 2025-02-08 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_auto_20250208_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='pos',
            field=models.CharField(choices=[('laba rugi', 'laba rugi'), ('neraca', 'neraca')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
