# Generated by Django 3.1.12 on 2025-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0008_profil_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='master_akun',
            field=models.CharField(choices=[('aktiva', 'aktiva'), ('passiva', 'passiva'), ('pendapatan', 'pendapatan'), ('beban', 'beban')], max_length=30),
        ),
    ]
