# Generated by Django 3.1.12 on 2025-02-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0009_auto_20250208_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='saldo_normal',
            field=models.CharField(choices=[('debit', 'debit'), ('kredit', 'kredit')], max_length=30),
        ),
    ]
