# Generated by Django 3.1.12 on 2025-02-09 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0010_auto_20250208_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalumum',
            name='uraian',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
