# Generated by Django 3.1.12 on 2025-02-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0011_jurnalumum_uraian'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalumum',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akun.user'),
            preserve_default=False,
        ),
    ]
