# Generated by Django 3.1.12 on 2025-02-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0012_jurnalumum_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akun.user'),
            preserve_default=False,
        ),
    ]
