# Generated by Django 3.1.12 on 2025-02-10 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0013_profil_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalumum',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
